image: gitlab.pilichiewicz.pl:5050/dockercorewindows/builder_choco:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - choco pack
    - Copy-Item -Path *.nupkg -Destination \\pilisrvfile01.pilichiewicz.local\exchange\;
  only:
    - master
