stages:
  - package
  - push-public
  - test-installation
  - push-official

variables:
  WORKING_DIR: "./fileseek"

default:
  tags:
    - Application_Build

package_choco:
  stage: package
  script:
    - Write-Host "Switching to working directory $env:WORKING_DIR"
    - Set-Location -Path $env:WORKING_DIR
    - $f='tools/chocolateyinstall.ps1'; Get-Content $f | Where-Object { $_ -notmatch '^\s*#' } | ForEach-Object { $_ -replace '(^.*?)\s*?[^`]#.*','$1' } | Out-File "$($f + '.~')" -Encoding utf8; Move-Item -Force "$($f + '.~')" $f
    - $f='tools/chocolateyuninstall.ps1'; Get-Content $f | Where-Object { $_ -notmatch '^\s*#' } | ForEach-Object { $_ -replace '(^.*?)\s*?[^`]#.*','$1' } | Out-File "$($f + '.~')" -Encoding utf8; Move-Item -Force "$($f + '.~')" $f
    - $f='tools/chocolateybeforemodify.ps1'; Get-Content $f | Where-Object { $_ -notmatch '^\s*#' } | ForEach-Object { $_ -replace '(^.*?)\s*?[^`]#.*','$1' } | Out-File "$($f + '.~')" -Encoding utf8; Move-Item -Force "$($f + '.~')" $f
    - choco pack
  artifacts:
    paths:
      - fileseek/*.nupkg
    expire_in: 1 week

push_to_public:
  stage: push-public
  dependencies:
    - package_choco
  script:
    - Write-Host "Switching to working directory $env:WORKING_DIR"
    - Set-Location -Path $env:WORKING_DIR
    - choco push --force -s "https://nexus.srv.pilichiewicz.local/repository/chocolatey-repo-public/" --api-key=$env:NEXUS_API_KEY
  allow_failure: false

test_installation:
  stage: test-installation
  dependencies:
    - push_to_public
  script:
    - Write-Host "Switching to working directory $env:WORKING_DIR"
    - Set-Location -Path $env:WORKING_DIR
    - Write-Host "Installing package from public repository"
    - choco install fileseek --force --confirm -s "https://nexus.srv.pilichiewicz.local/repository/chocolatey-repo-public/;https://nexus.srv.pilichiewicz.local/repository/chocolatey-repo-mirror/"
    - Write-Host "Testing the installation" 
    - Test-Path "C:\Program Files\FileSeek"  # Example validation step, adjust to match the package installation path
  allow_failure: false

push_to_offical:
  stage: push-official
  dependencies:
    - test_installation
  script:
    - Write-Host "Switching to working directory $env:WORKING_DIR"
    - Set-Location -Path $env:WORKING_DIR
    - Write-Host "Pushing package to Chocolatey Community repository"
    - choco push --api-key=$env:CHOCOLATEY_API_KEY
  allow_failure: false
  artifacts:
    paths:
      - fileseek/*.nupkg
    expire_in: 1 week