stages:
  - build
  - test-installation
  - push-public  
  - push-official

variables:
  WORKING_DIR: "$CI_PROJECT_DIR/fileseek"

default:
  image: "gitlab.pilichiewicz.pl:5050/docker/core_builder/windows/builder_choco:latest"
  tags:
    - Windows_Choco

package_choco:
  stage: build
  script:
    - Write-Host "Switching to working directory $env:WORKING_DIR"
    - Set-Location -Path $env:WORKING_DIR
    - $f='tools/chocolateyinstall.ps1'; Get-Content $f | Where-Object { $_ -notmatch '^\s*#' } | ForEach-Object { $_ -replace '(^.*?)\s*?[^`]#.*','$1' } | Out-File "$($f + '.~')" -Encoding utf8; Move-Item -Force "$($f + '.~')" $f
    - $f='tools/chocolateyuninstall.ps1'; Get-Content $f | Where-Object { $_ -notmatch '^\s*#' } | ForEach-Object { $_ -replace '(^.*?)\s*?[^`]#.*','$1' } | Out-File "$($f + '.~')" -Encoding utf8; Move-Item -Force "$($f + '.~')" $f
    - $f='tools/chocolateybeforemodify.ps1'; Get-Content $f | Where-Object { $_ -notmatch '^\s*#' } | ForEach-Object { $_ -replace '(^.*?)\s*?[^`]#.*','$1' } | Out-File "$($f + '.~')" -Encoding utf8; Move-Item -Force "$($f + '.~')" $f
    - choco pack
  artifacts:
    paths:
      - ${WORKING_DIR}/*.nupkg
    expire_in: 1 week

test_installation:
  stage: test-installation
  dependencies:
    - package_choco
  script:
    - Write-Host "Switching to working directory $env:WORKING_DIR"
    - Set-Location -Path $env:WORKING_DIR
    - Write-Host "Installing package from public repository"
    - powershell.exe -NoProfile -ExecutionPolicy Bypass -File $env:CI_PROJECT_DIR/test_script.ps1
  allow_failure: false    

push_to_public:
  stage: push-public
  dependencies:
    - package_choco
  script:
    - Write-Host "Switching to working directory $env:WORKING_DIR"
    - Set-Location -Path $env:WORKING_DIR
    - choco push --force -s "http://nexus.srv.pilichiewicz.local/repository/chocolatey-repo-public/" --api-key=$env:NEXUS_API_KEY
  allow_failure: true

push_to_offical:
  stage: push-official
  when: manual
  dependencies:
    - package_choco
  script:
    - Write-Host "Switching to working directory $env:WORKING_DIR"
    - Set-Location -Path $env:WORKING_DIR
    - Write-Host "Pushing package to Chocolatey Community repository"
    - choco push -s "https://community.chocolatey.org/api/v2/" --api-key=$env:CHOCOLATEY_API_KEY
  allow_failure: true